NUMBER_OF_HOW_MANY_DIGIT_IS_IN_THE_KEY = 1
# TEXT_TO_ENCRYPT = 'Congressional'
TEXT_TO_ENCRYPT = 'Congressionalcongressionalleadersintheusreachedabipartisandealearlythismorningtoprovidebntohelpukraineandeuropeanalliesreportstheassociatedpresspresidentjoebidenoriginallyrequestedbnformilitaryhumanitarianandeconomicaidbutthebackingfrombothpartieswassostrongthatthefigureclimbedtobnonmondayandbnyesterdayweregoingtosupportthemagainsttyrannyoppressionviolentactsofsubjugationbidensaidatthewhitehousepartyleadersarehopingtogetthepagemeasurethroughthehousetodayandthesenatebytheendoftheweekbutthetimingofthelatterremainsunclear'
ATTACK_TIME = 300
